#!/usr/bin/env node

/**
 * Test server with multiline descriptions
 * Generated by MCP Creator - https://github.com/modelcontextprotocol/mcp
 */

const { Server } = require('@modelcontextprotocol/sdk/server/index.js');
const { StdioServerTransport } = require('@modelcontextprotocol/sdk/server/stdio.js');
const { 
  CallToolRequestSchema, 
  ErrorCode, 
  ListToolsRequestSchema, 
  McpError 
} = require('@modelcontextprotocol/sdk/types.js');

class testmultilineServer {
  constructor() {
    this.server = new Server(
      { name: "test-multiline", version: "1.0.0" },
      { capabilities: { tools: {} } }
    );
    
    this.setupHandlers();
  }

  setupHandlers() {
    this.server.setRequestHandler(ListToolsRequestSchema, async () => ({
      tools: [
        {
          name: "test",
          description: "Test server with multiline descriptions",
          inputSchema: {
            type: "object",
            properties: {
    __help: {
      type: "boolean",
      description: "Show help information\nThis is a multiline description\nwith multiple lines\nand special characters like 'quotes' and \"double quotes\"",
      required: false
    },
    __version: {
      type: "boolean",
      description: "Show version information\nAnother multiline description\nwith tabs\tand\r\ncarriage returns",
      required: false
    }
            },
            required: []
          }
        }
      ]
    }));

    this.server.setRequestHandler(CallToolRequestSchema, async (request) => {
      const { name, arguments: args } = request.params;
      
      if (name === "test") {
        return await this.executeTool(args);
      }
      
      throw new McpError(ErrorCode.MethodNotFound, `Unknown tool: ${name}`);
    });
  }

  async executeTool(args) {
    try {
      // Simulación de ejecución del comando
      const result = `Executed test with args: ${JSON.stringify(args)}`;
      
      return {
        content: [
          {
            type: "text",
            text: result
          }
        ]
      };
    } catch (error) {
      return {
        content: [
          {
            type: "text", 
            text: `Error: ${error.message}`
          }
        ]
      };
    }
  }

  async run() {
    const transport = new StdioServerTransport();
    await this.server.connect(transport);
    console.error("test-multiline MCP Server running on stdio");
  }
}

if (require.main === module) {
  const server = new testmultilineServer();
  server.run().catch(console.error);
}

module.exports = testmultilineServer;
